swagger: '2.0'
info:
  description: Api Documentation
  version: '1.1'
  title: Merchant-API
  termsOfService: 'urn:tos'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /merchant-api
tags:
  - name: merchant-api-controller
    description: Merchant API Controller
paths:
  /merchants:
    get:
      tags:
        - merchant-api-controller
      summary: getAllMerchants
      operationId: getAllMerchantsUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Merchant'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - merchant-api-controller
      summary: createNewMerchant
      operationId: createNewMerchantUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: newMerchant
          description: newMerchant
          required: true
          schema:
            $ref: '#/definitions/NewMerchant'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/merchants/{merchantID}':
    get:
      tags:
        - merchant-api-controller
      summary: getMerchantByID
      operationId: getMerchantByIDUsingGET
      produces:
        - application/json
      parameters:
        - name: merchantID
          in: path
          description: merchantID
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Merchant'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Merchant:
    type: object
    properties:
      corporateName:
        type: string
      id:
        type: integer
        format: int64
      merchantID:
        type: string
      taxID:
        type: string
    title: Merchant
  NewMerchant:
    type: object
    properties:
      corporateName:
        type: string
      merchantID:
        type: string
      taxID:
        type: string
    title: NewMerchant
